### ISSUE TITLE
Seemingly minor polygon issues result in miles of exceptions, terminating in bizarre behavior

### ISSUE THREAD

**Issue by JansenSmith** [CommonWealthRobotics/CaDoodle-Application#23]
Operations are taking a long time, eventually finish, but they seem to be unreplicable upon reloading.
I think CaDoodle might need to incorporate MeshLab somehow.
```
java.lang.NumberFormatException: This set of points is not a valid polygon
	at eu.mihosoft.vrl.v3d.Plane.computeNormal(Plane.java:144)
	at eu.mihosoft.vrl.v3d.Plane.createFromPoints(Plane.java:102)
	at eu.mihosoft.vrl.v3d.Polygon.<init>(Polygon.java:115)
	at eu.mihosoft.vrl.v3d.Polygon.fromPoints(Polygon.java:451)
	at eu.mihosoft.vrl.v3d.Polygon.fromPointsAllowDegenerate(Polygon.java:427)
	at eu.mihosoft.vrl.v3d.STL.file(STL.java:92)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:93)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:84)
	at com.neuronrobotics.bowlerstudio.scripting.StlLoader.inlineScriptRun(StlLoader.java:15)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:521)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:1114)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.flaten(ScriptingEngine.java:134)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.AddFromFile.process(AddFromFile.java:60)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.process(CaDoodleFile.java:212)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.initialize(CaDoodleFile.java:123)
	at com.commonwealthrobotics.MainController.lambda$setupFile$9(MainController.java:688)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.NumberFormatException: This set of points is not a valid polygon
	at eu.mihosoft.vrl.v3d.Plane.computeNormal(Plane.java:144)
	at eu.mihosoft.vrl.v3d.Plane.createFromPoints(Plane.java:102)
	at eu.mihosoft.vrl.v3d.Polygon.<init>(Polygon.java:115)
	at eu.mihosoft.vrl.v3d.Polygon.fromPoints(Polygon.java:451)
	at eu.mihosoft.vrl.v3d.Polygon.fromPointsAllowDegenerate(Polygon.java:427)
	at eu.mihosoft.vrl.v3d.STL.file(STL.java:92)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:93)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:84)
	at com.neuronrobotics.bowlerstudio.scripting.StlLoader.inlineScriptRun(StlLoader.java:15)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:521)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:1114)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.flaten(ScriptingEngine.java:134)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.AddFromFile.process(AddFromFile.java:60)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.process(CaDoodleFile.java:212)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.initialize(CaDoodleFile.java:123)
	at com.commonwealthrobotics.MainController.lambda$setupFile$9(MainController.java:688)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.NumberFormatException: This set of points is not a valid polygon
	at eu.mihosoft.vrl.v3d.Plane.computeNormal(Plane.java:144)
	at eu.mihosoft.vrl.v3d.Plane.createFromPoints(Plane.java:102)
	at eu.mihosoft.vrl.v3d.Polygon.<init>(Polygon.java:115)
	at eu.mihosoft.vrl.v3d.Polygon.fromPoints(Polygon.java:451)
	at eu.mihosoft.vrl.v3d.Polygon.fromPointsAllowDegenerate(Polygon.java:427)
	at eu.mihosoft.vrl.v3d.STL.file(STL.java:92)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:93)
	at com.neuronrobotics.bowlerstudio.vitamins.Vitamins.get(Vitamins.java:84)
	at com.neuronrobotics.bowlerstudio.scripting.StlLoader.inlineScriptRun(StlLoader.java:15)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineScriptRun(ScriptingEngine.java:521)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.inlineFileScriptRun(ScriptingEngine.java:1114)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine.flaten(ScriptingEngine.java:134)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.AddFromFile.process(AddFromFile.java:60)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.process(CaDoodleFile.java:212)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.initialize(CaDoodleFile.java:123)
	at com.commonwealthrobotics.MainController.lambda$setupFile$9(MainController.java:688)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3585)
	at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.ensureCapacity(ObservableIntegerArrayImpl.java:254)
	at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.growCapacity(ObservableIntegerArrayImpl.java:245)
	at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.addAllInternal(ObservableIntegerArrayImpl.java:81)
	at javafx.base/com.sun.javafx.collections.ObservableIntegerArrayImpl.addAll(ObservableIntegerArrayImpl.java:94)
	at eu.mihosoft.vrl.v3d.CSGtoJavafx.meshFromPolygon(CSGtoJavafx.java:118)
	at eu.mihosoft.vrl.v3d.CSG.toJavaFXMeshSimple(CSG.java:1756)
	at eu.mihosoft.vrl.v3d.CSG.toJavaFXMesh(CSG.java:1732)
	at eu.mihosoft.vrl.v3d.CSG.newMesh(CSG.java:273)
	at eu.mihosoft.vrl.v3d.CSG.getMesh(CSG.java:262)
	at com.neuronrobotics.bowlerstudio.creature.ThumbnailImage.get(ThumbnailImage.java:87)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.lambda$loadingImageFromUIThread$3(CaDoodleFile.java:437)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile$$Lambda$1385/0x0000767d9cb1d9b8.run(Unknown Source)
	at com.neuronrobotics.bowlerstudio.BowlerKernel.lambda$runLater$7(BowlerKernel.java:813)
	at com.neuronrobotics.bowlerstudio.BowlerKernel$$Lambda$1040/0x0000767d9c84c6f0.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$72/0x0000767d9c08ecf0.run(Unknown Source)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl$$Lambda$71/0x0000767d9c08e880.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication$$Lambda$57/0x0000767d9c034e18.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.Exception: UI Thread Exception here!
	at com.neuronrobotics.bowlerstudio.BowlerKernel.runLater(BowlerKernel.java:799)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.loadingImageFromUIThread(CaDoodleFile.java:437)
	at com.neuronrobotics.bowlerstudio.scripting.cadoodle.CaDoodleFile.save(CaDoodleFile.java:402)
	at com.commonwealthrobotics.ActiveProject.save(ActiveProject.java:174)
	at com.commonwealthrobotics.controls.SelectionSession.lambda$save$29(SelectionSession.java:1161)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
Likely related:
![image](https://github.com/user-attachments/assets/f2efba7f-83f6-47a3-94cc-2e797376c833)

**Comment by madhephaestus** [comment]
meshing engine has been totally revamped
