### ISSUE TITLE
Large memory usage for large mesh files causing out of memory exception

### ISSUE THREAD

**Issue by JansenSmith** [CommonWealthRobotics/CaDoodle-Application#25]
It's a large STL being grouped, but this machine has more than enough mem for the operation.
![Screenshot from 2024-11-06 10-26-45](https://github.com/user-attachments/assets/92b0a864-7391-4b31-bfa1-c588e7055fc1)

```
Exception in thread "addOpperation Thread 1" java.lang.OutOfMemoryError: Java heap space
Nov 06, 2024 11:15:29 AM sun.awt.X11.XToolkit processException
WARNING: Exception on Toolkit thread
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedList.listIterator(LinkedList.java:872)
	at java.base/java.util.AbstractList.listIterator(AbstractList.java:311)
	at java.base/java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:238)
	at java.desktop/sun.awt.X11.XWM.isStateChange(XWM.java:1219)
	at java.desktop/sun.awt.X11.XFramePeer.handlePropertyNotify(XFramePeer.java:313)
	at java.desktop/sun.awt.X11.XBaseWindow.dispatchEvent(XBaseWindow.java:1173)
	at java.desktop/sun.awt.X11.XBaseWindow.dispatchToWindow(XBaseWindow.java:1116)
	at java.desktop/sun.awt.X11.XToolkit.dispatchEvent(XToolkit.java:616)
	at java.desktop/sun.awt.X11.XToolkit.run(XToolkit.java:731)
	at java.desktop/sun.awt.X11.XToolkit.run(XToolkit.java:647)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by madhephaestus** [comment]
show me the mem usage graph in visualvm with any memory usage graph please. just the exception is not enough information to do anything with

**Comment by madhephaestus** [comment]
@JansenSmith I just made a release that increased the base max ram usage from 8 to 16 gb. Can you try it now?

**Comment by madhephaestus** [comment]
this may be solved by https://github.com/CommonWealthRobotics/CaDoodle-Application/commit/d8e87301edbbdec45acba25d28f3001c4d5a93b3
